"""Generate docs/index.json so Blender can install this add-on directly.

    python3 make_index.py ../stroke-map-pipeline/builds/stroke_map_pipeline_ao_v3.29.0_20260818-1716.zip

Blender 4.2+ can add a REMOTE REPOSITORY: the user pastes one URL into
Preferences > Get Extensions > Repositories, and from then on the add-on
appears in their extensions list, installs in one click, and updates itself
when a new version is published. No browser download, which also sidesteps
Safari expanding the archive on macOS and leaving a folder Blender will not
accept.

THE INDEX IS GENERATED BY BLENDER, NOT BY THIS SCRIPT. `blender --command
extension server-generate` owns the schema; hand-rolling the JSON means
silently drifting from it the first time Blender adds a field. All this does
is run that command and repoint `archive_url`.

WHY REPOINT IT: server-generate assumes the zips sit beside index.json and
writes a relative "./name.zip". Serving them that way would mean committing
a binary per version into a repo that is otherwise text. Pointing at the
GitHub release asset instead keeps Releases as the single source of truth for
builds and leaves this repo small.

So the ORDER MATTERS: publish the release first, then run this. The index
carries a sha256 of the archive, and Blender checks it -- a stale index fails
loudly at install rather than delivering the wrong file, which is the good
failure to have.
"""
import argparse
import glob
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import urllib.request

ROOT = os.path.dirname(os.path.abspath(__file__))
REPO = "wavyDZ/stroke-map-pipeline-releases"
DOCS = os.path.join(ROOT, "docs")


def find_blender():
    """Blender executable for this platform, or None."""
    if sys.platform == "darwin":
        cands = ["/Applications/Blender.app/Contents/MacOS/Blender"]
        cands += sorted(glob.glob(
            "/Applications/Blender*.app/Contents/MacOS/Blender"), reverse=True)
    elif sys.platform == "win32":
        cands = sorted(glob.glob(
            r"C:\Program Files\Blender Foundation\Blender *\blender.exe"),
            reverse=True)
    else:
        cands = []
        found = shutil.which("blender")
        if found:
            cands.append(found)
    for c in cands:
        if os.path.isfile(c):
            return c
    return shutil.which("blender")


def release_url(zip_path, version):
    """Where the asset actually lives -- ASKED, not assumed.

    This used to construct the URL as
    `.../releases/download/v{version}/{basename}`, which bakes in two guesses:
    that the tag is exactly "v" plus the version, and that the asset kept the
    filename we built it with. Both are things a human types into a web form
    at 4am.

    THE FIRST GUESS FAILED ON ITS FIRST REAL USE. v3.30.0 was published under
    the tag `v.3.30.0` -- one extra dot -- so the constructed URL returned 404
    while the real one returned 200. An index built from it would have
    advertised a dead link to every user; the mistake was invisible from the
    machine that made it, where the add-on is installed from source.

    So the URL now comes from the GitHub API: find the release whose asset
    matches this file by NAME AND SIZE, and take the `browser_download_url`
    GitHub itself reports. Whatever the tag is spelled like, that URL is
    right by construction. It also fails immediately and with a clear reason
    when the release has not been published yet, instead of producing an
    index that only breaks later on somebody else's machine.
    """
    name = os.path.basename(zip_path)
    size = os.path.getsize(zip_path)
    api = f"https://api.github.com/repos/{REPO}/releases"
    try:
        with urllib.request.urlopen(api) as r:
            releases = json.load(r)
    except Exception as e:
        sys.exit(f"could not reach the GitHub API to locate the release: {e}")

    for rel in releases:
        for asset in rel.get("assets", []):
            if asset["name"] == name:
                if asset["size"] != size:
                    sys.exit(
                        f"'{name}' is published under tag {rel['tag_name']} "
                        f"but is {asset['size']} bytes there against "
                        f"{size} locally -- a different build was uploaded")
                print(f"  found under tag {rel['tag_name']}")
                return asset["browser_download_url"]

    tags = ", ".join(r["tag_name"] for r in releases) or "(none)"
    sys.exit(f"no published release has an asset named '{name}'.\n"
             f"Existing tags: {tags}\n"
             f"Publish the release and attach this zip first -- see "
             f"RELEASING.md, the index must be built after the release.")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("zips", nargs="+", help="built .zip files to list")
    ap.add_argument("--blender", help="path to the Blender executable")
    args = ap.parse_args()

    blender = args.blender or find_blender()
    if not blender:
        sys.exit("could not find Blender -- pass --blender")

    with tempfile.TemporaryDirectory() as tmp:
        for z in args.zips:
            if not os.path.isfile(z):
                sys.exit(f"no such file: {z}")
            shutil.copy2(z, os.path.join(tmp, os.path.basename(z)))
        r = subprocess.run(
            [blender, "--factory-startup", "--command", "extension",
             "server-generate", f"--repo-dir={tmp}"],
            capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit(f"server-generate failed:\n{r.stdout}\n{r.stderr}")
        print(r.stdout.strip().splitlines()[-1] if r.stdout.strip() else "")
        with open(os.path.join(tmp, "index.json"), encoding="utf-8") as f:
            index = json.load(f)

    by_name = {os.path.basename(z): z for z in args.zips}
    for entry in index["data"]:
        local = None
        for name, path in by_name.items():
            if entry["version"] in name:
                local = path
                break
        if local is None:
            sys.exit(f"no zip matched {entry['id']} {entry['version']}")
        entry["archive_url"] = release_url(local, entry["version"])
        # Re-derive the hash from the file we are actually pointing at, so a
        # mismatched pair cannot get this far.
        h = hashlib.sha256(open(local, "rb").read()).hexdigest()
        if entry["archive_hash"] != f"sha256:{h}":
            sys.exit(f"hash mismatch for {local}")
        print(f"  {entry['id']} {entry['version']} -> {entry['archive_url']}")

    os.makedirs(DOCS, exist_ok=True)
    out = os.path.join(DOCS, "index.json")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        json.dump(index, f, indent=2)
        f.write("\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
