"""Generate docs/index.json so Blender can install this add-on directly.

    python3 make_index.py ../stroke-map-pipeline/builds/stroke_map_pipeline_ao_v3.29.0_20260818-1716.zip

Blender 4.2+ can add a REMOTE REPOSITORY: the user pastes one URL into
Preferences > Get Extensions > Repositories, and from then on the add-on
appears in their extensions list, installs in one click, and updates itself
when a new version is published. No browser download, which also sidesteps
Safari expanding the archive on macOS and leaving a folder Blender will not
accept.

THE INDEX IS GENERATED BY BLENDER, NOT BY THIS SCRIPT. `blender --command
extension server-generate` owns the schema; hand-rolling the JSON means
silently drifting from it the first time Blender adds a field. All this does
is run that command and repoint `archive_url`.

WHY REPOINT IT: server-generate assumes the zips sit beside index.json and
writes a relative "./name.zip". Serving them that way would mean committing
a binary per version into a repo that is otherwise text. Pointing at the
GitHub release asset instead keeps Releases as the single source of truth for
builds and leaves this repo small.

So the ORDER MATTERS: publish the release first, then run this. The index
carries a sha256 of the archive, and Blender checks it -- a stale index fails
loudly at install rather than delivering the wrong file, which is the good
failure to have.
"""
import argparse
import glob
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.abspath(__file__))
REPO = "wavyDZ/stroke-map-pipeline-releases"
DOCS = os.path.join(ROOT, "docs")


def find_blender():
    """Blender executable for this platform, or None."""
    if sys.platform == "darwin":
        cands = ["/Applications/Blender.app/Contents/MacOS/Blender"]
        cands += sorted(glob.glob(
            "/Applications/Blender*.app/Contents/MacOS/Blender"), reverse=True)
    elif sys.platform == "win32":
        cands = sorted(glob.glob(
            r"C:\Program Files\Blender Foundation\Blender *\blender.exe"),
            reverse=True)
    else:
        cands = []
        found = shutil.which("blender")
        if found:
            cands.append(found)
    for c in cands:
        if os.path.isfile(c):
            return c
    return shutil.which("blender")


def release_url(zip_path, version):
    """Where the asset actually lives, once the release is published.

    Built from the tag and the file's OWN name rather than a tidy name we
    wish it had: the asset keeps whatever filename was uploaded, and an
    archive_url that does not match it 404s at install time.
    """
    return (f"https://github.com/{REPO}/releases/download/"
            f"v{version}/{os.path.basename(zip_path)}")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("zips", nargs="+", help="built .zip files to list")
    ap.add_argument("--blender", help="path to the Blender executable")
    args = ap.parse_args()

    blender = args.blender or find_blender()
    if not blender:
        sys.exit("could not find Blender -- pass --blender")

    with tempfile.TemporaryDirectory() as tmp:
        for z in args.zips:
            if not os.path.isfile(z):
                sys.exit(f"no such file: {z}")
            shutil.copy2(z, os.path.join(tmp, os.path.basename(z)))
        r = subprocess.run(
            [blender, "--factory-startup", "--command", "extension",
             "server-generate", f"--repo-dir={tmp}"],
            capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit(f"server-generate failed:\n{r.stdout}\n{r.stderr}")
        print(r.stdout.strip().splitlines()[-1] if r.stdout.strip() else "")
        with open(os.path.join(tmp, "index.json"), encoding="utf-8") as f:
            index = json.load(f)

    by_name = {os.path.basename(z): z for z in args.zips}
    for entry in index["data"]:
        local = None
        for name, path in by_name.items():
            if entry["version"] in name:
                local = path
                break
        if local is None:
            sys.exit(f"no zip matched {entry['id']} {entry['version']}")
        entry["archive_url"] = release_url(local, entry["version"])
        # Re-derive the hash from the file we are actually pointing at, so a
        # mismatched pair cannot get this far.
        h = hashlib.sha256(open(local, "rb").read()).hexdigest()
        if entry["archive_hash"] != f"sha256:{h}":
            sys.exit(f"hash mismatch for {local}")
        print(f"  {entry['id']} {entry['version']} -> {entry['archive_url']}")

    os.makedirs(DOCS, exist_ok=True)
    out = os.path.join(DOCS, "index.json")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        json.dump(index, f, indent=2)
        f.write("\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
